name: thanks

on:
  issue_comment:
    types: created
  workflow_dispatch: # manual

jobs:
  thanks:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v7
        id: comment_script
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment_id = context.payload.comment.id;
            console.log(`comment_id: ${comment_id}`);

            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // create comment thanking contributor
            const comment = await github.rest.issues.createComment({
              repo, owner, issue_number,
              body: "Thank you for your comment!"
            });
            console.log(`comment id: ${comment.data.id}`);
            console.log(comment.data);

            // make comment id available to subsequent steps
            return comment.data.id;

      - run: echo 'comment id=${{ steps.comment_script.outputs.result }}'